Order1 = input ("beli baju :")
Order2 = input ("beli celana :")
Order3 = input ("beli sepatu :")
Order4 = input ("beli topi :")
Order5 = input ("beli tas :")
Order6 = input ("beli outer :")
Order7 = input ("beli kacamata :")
Order8 = input ("beli kendaraan :")
Order9 = input ("beli makanan :")
Order10 = input ("beli minuman :")
Order11 = input ("beli snack :")
Order12 = input ("beli gadget :")
Order13 = input ("beli barang:")
Order14 = input ("beli alat tulis :")
Order15 = input ("beli buah :")

print ("\n ===Daftar pesanan===")
print ("baju :", Order1)
print ("celana :", Order2)
print ("sepatu :", Order3)
print ("topi :", Order4)
print ("tas :", Order5)
print ("outer :", Order6)
print ("kacamata :", Order7)
print ("kendaraan :", Order8)
print ("makanan :", Order9)
print ("minuman :", Order10)
print ("snack :", Order11)
print ("gadget :", Order12)
print ("barang :", Order13)
print ("alat tulis :", Order14)
print ("buah :", Order15)
