s = input("masukkan merk sepatu :")
k = input("masukkan merk kaos kaki :")
umur = int(input("masukkan umur :"))
nama = input("masukkan nama :")
PC = input("masukkan merk pc :")
monitor = input("masukkan merk monitor :")
mouse = input("masukkan merk mouse :")
keyboard = input("masukkan merk keyboard :")
mb = input("masukkan merk motherboard :")
router = input("masukkan merk router :")
kabel = input("masukkan jenis kabel :")
ram = input("masukkan kapasitas RAM :")
casan = input("masukkan merk casan :")
eathernet = int(input("masukkan ukuran kabel eathernet :"))
itu_lah = input("masukkan itulah :")

print("\n\n\n === data parrang ===")
print("merks sepatu :",s)
print("merk kaos kaki :",k)
print("umur :",umur)
print("nama :",nama)
print("merk pc :",PC)
print("merk monitor :",monitor)
print("merk mouse:",mouse)
print("merk keyboard:",keyboard)
print("merk motherboard:",mb)
print("merk router:",router)
print("merk kabel:",kabel)
print("kapasitas ram:",ram)
print("merk casan:",casan)
print("ukuran kabel eathernet:",eathernet)
print("merk itulah:",itu_lah)
