umur = ("massukan umur:")
nama = ("masukkan nama:")
sekolah = input ("masukkan sekolah:")
makanan = input("masukkan makanan:")
minuman = input(" masukkan minuman:")
warna = input("masukkan warna:")
alamat = input("masukkan alamat:")
hobby = input("masukkan hobby:")
ayah =input ("masukkan ayah:")
kakak = input("masukkan adek:")
adek = input("masukkan adek:")
ibu =input ("masukkan ibu:")
hewan =input ("masukkan hewan:")
baju =input ("masukkan baju:")
celana =input ("masukkan celana:")
kursi =input ("masukkan kursi:")
hp =input ("masukkan hp:")
rumah =input ("massukkan rumah:")
komputer =input ("masukkan lomputer:")
kabel =input("masukkan kabel:")
a =input("masukkan a:")
b =input ("masukkan b:")
c =input("masukkan c:")
d = input("masukkan d:")
e = input("masukkan d:")
f =input ("masukkan e:")
g = input("masukkan g:")
h = input("masukkan h:")
i =input ("masukkan i:")
j = input("masukkan j:")
print ("\n===data pribadi===")
print ("umur:",umur)
print ("nama:",nama)
print ("sekolah:",sekolah)
print ("makanan:",makanan)
print ("minuman:",minuman)
print ("warna",warna)
print ("alamat:",alamat)
print ("hobby:",hobby)
print ("ayah:",ayah)
print ("adek:",adek)
print ("kakak:",kakak)
print ("ibu:",ibu)
print ("hewan:",hewan)
print ("baju:",baju)
print ("celana:",celana)
print ("kursi:",kursi)
print ("hp:",hp)
print ("rumah:",rumah)
print ("komputer:",komputer)
print ("kabel",kabel)
print ("a:",a)
print ("b:",b)
print ("c:",c)
print ("d:",d)
print ("e:",e)
print ("f:",f)
print ("g:",g)
print ("h:",h)
print ("i:",i)
print ("j:",j)
