nilai = int (input("masukkan nilai;"))
if nilai >= 70:
   print ("lulus")   


nilai = 80
if nilai >= 72:
     print("lulus")
else:
    print("tidak lulus")






nilai = 60

if nilai >= 95:
    print("lulus")    
elif nilai >= 90:
    print("tunggu konfirmasi")
elif nilai >= 85:
    print("tunggu konfirmasi")
else:
    print("tidak lulus")




nilai = 80
absen = 90

if nilai >= 75 and absen >= 80:
    print("Lulus")
